### ISSUE TITLE
Inferring schema

### ISSUE THREAD

**Issue by bombsimon** [jsontypedef/json-typedef-go#6]
It would be great if this package supported an API for inferring schema similar to https://github.com/jsontypedef/json-typedef-infer.

I would be open to work on such feature but this project seems a bit dead so I would love some response before I get starting on that.

**Comment by ucarion** [comment]
I don't think it's necessary to implement this functionality directly within this library, so I'm inclined to not accept such a feature. This library is dormant largely because it is feature-complete, with minimal objectives.

If I'm mistaken, and there's a reason inference has to be done within this module, please re-open and let me know!
